### ISSUE TITLE
Legacy Branch issue

### ISSUE THREAD

**Issue by PSNisMasterOga** [Reimnop/Catalyst#8]
I found out there was an update so i changed from potassium to Catalyst and did all the necessary steps, but when going on a level it erased basically every object in the level ( yes this did technically make it quicker ). This was in the legacy branch

**Comment by RTMecha** [comment]
Yeah some levels don't work well with Catalyst. I believe it could be because some objects appear before the level even begins to or some values are out of the range of accepted values so the objects just break, or it could be something completely random that I haven't looked into with this mod yet

**Comment by PSNisMasterOga** [comment]
I also tried out the dev branch and every level i tried worked apart from one. The interesting thing is that the one that didnt work was a level that cant be played on the legacy branch (rally the troops) so idk if that means anything

**Comment by RTMecha** [comment]
Dev branch levels can actually be played on Legacy, there's just a thing that blocks you from doing so. Also interesting that most levels work on the dev branch

**Comment by Reimnop** [comment]
Can you send me the level workshop link and the relevant logs from Catalyst?

**Comment by Reimnop** [comment]
Fixed. Download it [here](https://github.com/Reimnop/Catalyst/releases/tag/2.1.1).
